In [5]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.graphics.tsaplots import plot_pacf
import plotly.express as px

import datetime
from collections import defaultdict

import warnings
from IPython import get_ipython
get_ipython().config.InlineBackend.figure_format = 'retina'
warnings.simplefilter("ignore")

In [ ]:
df_stores = pd.read_csv("./stores.csv")
df_stores = df_stores.set_index('store_nbr')
df_stores

In [ ]:
a = [1,2,3]
b = [4,5,6]

In [ ]:
a.append(b)
print(a)

In [ ]:
a.extend(b)
print(a)


In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(np.setdiff1d(b, a))

In [ ]:
import numpy as np

a = np.array([[1,2,3],[0,1,4]])
print (a.size)

In [1]:
import pandas as pd
sales = {'account': ['Jones LLC', 'Alpha Co', 'Blue Inc'],
         'Jan': [150, 200, 50],
         'Feb': [200, 210, 90],
         'Mar': [140, 215, 95]}
df_sales = pd.DataFrame.from_dict(sales)
df_sales.drop(df_sales.index[2])
print(df_sales)

     account  Jan  Feb  Mar
0  Jones LLC  150  200  140
1   Alpha Co  200  210  215
2   Blue Inc   50   90   95


In [2]:
import pandas as pd
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])
print(sr1[sr1.isin(sr2)])

1    2
3    4
dtype: int64


In [3]:
import pandas as pd
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])
print(sr1[~sr1.isin(sr2)])

0    1
2    3
4    5
dtype: int64


In [6]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate([b, a], axis=0)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [8]:
np.concatenate([b, a], axis=1)

array([[1, 1, 1, 1, 1, 0, 1, 2, 3, 4],
       [1, 1, 1, 1, 1, 5, 6, 7, 8, 9]])

In [9]:
np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])